name: Auto Release

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  check-release:
    name: Check for Release
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
      changelog: ${{ steps.check.outputs.changelog }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if this is a release commit
        id: check
        run: |
          # Check if package.json version changed
          VERSION_CHANGED=$(git diff HEAD~1 HEAD -- package.json | grep '"version"' || echo "")
          CHANGELOG_CHANGED=$(git diff HEAD~1 HEAD -- CHANGELOG.md | grep -E '^\+.*##.*[0-9]+\.[0-9]+\.[0-9]+' || echo "")
          
          if [ ! -z "$VERSION_CHANGED" ] && [ ! -z "$CHANGELOG_CHANGED" ]; then
            VERSION=$(node -p "require('./package.json').version")
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=v$VERSION" >> $GITHUB_OUTPUT
            
            # Extract changelog for this version
            awk '/^## / {if(found) exit; if(/\['$VERSION'\]/) found=1; next} found' CHANGELOG.md > /tmp/changelog.md
            CHANGELOG_CONTENT=$(cat /tmp/changelog.md)
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: check-release
    if: needs.check-release.outputs.should_release == 'true'
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check-release.outputs.version }}
          release_name: Release ${{ needs.check-release.outputs.version }}
          body: |
            ## 🚀 Release ${{ needs.check-release.outputs.version }}
            
            ${{ needs.check-release.outputs.changelog }}
            
            ### 📦 Installation
            
            ```bash
            npm install github:edgardamasceno-dev/beta-builders-design-system#${{ needs.check-release.outputs.version }}
            ```
            
            ### 🔗 Links
            
            - [Storybook Documentation](https://edgardamasceno-dev.github.io/beta-builders-design-system)
            - [Changelog](https://github.com/edgardamasceno-dev/beta-builders-design-system/blob/main/CHANGELOG.md)
            
            ---
            
            *This release was automatically created by GitHub Actions*
          draft: false
          prerelease: false 