name: CI

on:
  # Removed push triggers - only run on pull requests
  pull_request:
    branches: [main, development]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint check
        run: npm run lint

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
          fail_ci_if_error: false

  # E2E tests disabled temporarily
  # e2e:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Playwright browsers
  #       run: npx playwright install --with-deps
  #
  #     - name: Build Storybook
  #       run: npm run build-storybook
  #
  #     - name: Start Storybook server and run E2E tests
  #       run: |
  #         # Start static server in background
  #         npx http-server storybook-static -p 6006 -s &
  #         SERVER_PID=$!
  #         
  #         # Wait for server to start
  #         echo "Waiting for server to start..."
  #         sleep 5
  #         
  #         # Check if server is running
  #         curl -f http://localhost:6006 || (echo "Server failed to start" && exit 1)
  #         
  #         # Run E2E tests
  #         npm run test:e2e
  #         
  #         # Stop server
  #         kill $SERVER_PID
  #
  #     - name: Upload E2E test results
  #       uses: actions/upload-artifact@v4
  #       if: failure()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30 